#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond without using kill or killall

pid=$(pgrep -f "./4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
  # shellcheck disable=SC2086
  echo -17 > "/proc/$pid/oom_adj"
fi
