#!/usr/bin/env bash
# This script displays "Best School" 10 times; on the 9th iteration, it prints "Hi" below it

counter=1

while [ $counter -le 10 ]
do
  echo "Best School"
  if [ $counter -eq 9 ]; then
    echo "Hi"
  fi
  ((counter++))
done
